--- 


- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/tomcat
    state: directory
    recurse: yes
   
  
- name: change permission 
  ansible.builtin.file:
    path: /opt/tomcat/conf
    state: touch
    mode: g+r
    recurse: yes


- name: change permission 
  ansible.builtin.file:
    path: /opt/tomcat/conf
    state: touch
    mode: g+x

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/tomcat/webapps/
    state: directory
    recurse: yes
    owner: foo

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: foo

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: foo

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: foo


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  